
LootDB = {}

LootDB.Reagents = {
[L"Garlic"] = true,
[L"Black Pearl"] = true,
[L"Blood Moss"] = true,
[L"Mandrake Root"] = true,
[L"Nightshade"] = true,
[L"Spiders' Silk"] = true,
[L"Sulfurous Ash"] = true,
[L"Ginseng"] = true,
[L"Bone"] = true,
[L"Daemon Bone"] = true,
[L"Dragon's Blood"] = true,
[L"Fertile Dirt"] = true,
[L"Pig Iron"] = true,
[L"Batwing"] = true,
[L"Daemon Blood"] = true,
[L"Nox Crystal"] = true,
[L"Grave Dust"] = true,
}

LootDB.Materials = {
[L"Crystal Of Shame"] = true,

[L"Mark"] = true,
[L"Gate Travel"] = true,
[L"Recall"] = true,

[L"Quartz Grit"] = true,
[L"Corrosive Ash"] = true,
[L"Cursed Oilstone"] = true,
[L"Whetstone Of Enervation"] = true,

[L"Plucked Turkey"] = true,
[L"Giant Turkey Feather"] = true,

[L"Sand"] = true,
[L"Charcoal"] = true,
[L"Black Powder"] = true,
[L"Saltpeter"] = true,

[L"Irk's Brain"] = true,
[L"Gnaw's Fang"] = true,
[L"Lissith's Silk"] = true,
[L"Sabrix's Eye"] = true,

[L"Partially Digested Torso"] = true,
[L"Gelatanous Skull"] = true,
[L"Coagulated Legs"] = true,
[L"Spleen Of The Putrefier"] = true,

[L"Disintegrating Thesis Notes"] = true,
[L"Draconic Orb"] = true,

[L"Order From Minax"] = true,

[L"An Albino Squirrel Imprisoned In A Crystal"] = true,
[L"Hair Dye"] = true,
[L"Ethernally Corrupt Tree"] = true,
[L"Magled Head Of The Dread Horn"] = true,
[L"Horn Of The Dread Horn"] = true,
[L"Pristine Dread Horn"] = true,
[L"Dread Horn Tainted Mushroom"] = true,
[L"Paroxysmus' Dinner"] = true,
[L"Sweat Of Paroxysmus"] = true,
[L"Paroxysmus Swamp Dragon"] = true,
[L"String Of Parts Of Paroxysmus' Victims"] = true,
[L"Paroxysmus' Corroded Stein"] = true,
[L"Travesty's Fine Teakwood Tray"] = true,
[L"Travesty's Collection Of Shells"] = true,
[L"Travesty's Sushi Preparations"] = true,
[L"An Imprisoned Dog"] = true,
[L"Tragic Remains Of The Travesty"] = true,
[L"Corporeal Brume Statuette"] = true,
[L"A Ferret Imprisoned In A Crystal"] = true,
[L"Mantra Effervescence Statuette"] = true,
[L"Fetid Essence Statuette"] = true,
[L"Shimmering Effusion Statuette"] = true,
[L"Shimmering Crystals"] = true,
[L"Grizzled Skull Collection"] = true,
[L"Monsterous Interred Grizzle Maggots"] = true,
[L"Glob Of MOnsterous Interred Grizzle"] = true,
[L"Grizzled Mare Statuette"] = true,
[L"Tombstone Of The Damned"] = true,
[L"Horn Of Abyssal Inferno"] = true, 
[L"Stygian Dragon Head"] = true,
[L"Claw Of Slasher Of Veils"] = true, 

[L"Power Crystal"] = true,
[L"Clockwork Assembly"] = true,

[L"Scattered Crystals"] = true,
[L"Shattered Crystal"] = true,
[L"Crushed Crystals"] = true,
[L"Jagged Crystal"] = true,
[L"Crystal Pieces"] = true,
[L"Broken Crystals"] = true,

[L"Tiger Claw Key"] = true,
[L"Serpent Fang Key"] = true,
[L"Dragon Flame Key"] = true,

[L"Robe Of Rite"] = true,
[L"Exodus Summoning Rite"] = true,
[L"Exodus Summoning Altar"] = true,
[L"Exodus Sacrificial Dagger"] = true,

[L"Zoogi Fungus"] = true,

[L"Blight"] = true,
[L"Taint"] = true,
[L"Corruption"] = true,
[L"Muculent"] = true,
[L"Scourge"] = true,
[L"Putrefaction"] = true,

[L"Captured Essence"] = true,
[L"Grizzled Bones"] = true,
[L"Eye Of The Travesty"] = true,
[L"Lard Of Paroxysmus"] = true,
[L"Diseased Bark"] = true,
[L"Dread Horn Mane"] = true,
[L"Medusa Blood"] = true,

[L"Arrow"] = true,
[L"Crossbow Bolt"] = true,
[L"Clean Bandage"] = true,
[L"Compassion Sage"] = true,
[L"Arcane Gem"] = true,
[L"A Gargoyle's Pickaxe"] = true,
[L"Fire Horn"] = true,

[L"Cut Leather"] = true,
[L"Board"] = true,
[L"Ingots"] = true,
[L"Cloth"] = true,
[L"Feather"] = true,

[L"Sapphire"] = true,
[L"Star Sapphire"] = true,
[L"Ruby"] = true,
[L"Diamond"] = true,
[L"Citrine"] = true,
[L"Emerald"] = true,
[L"Amethyst"] = true,
[L"Amber"] = true,
[L"Tourmaline"] = true,

[L"Turquoise"] = true,
[L"Blue Diamond"] = true,
[L"Ecru Citrine"] = true,
[L"Perfect Emerald"] = true,
[L"Dark Sapphire"] = true,
[L"White Pearl"] = true,
[L"Brilliant Amber"] = true,
[L"Fire Ruby"] = true,

[L"Magical Residue"] = true,
[L"Enchanted Essence"] = true,
[L"Relic Fragment"] = true,

[L"Abyssal Cloth"] = true,
[L"Arcanic Rune Stone"] = true,
[L"Bottle Of Ichor"] = true,
[L"Boura Pelt"] = true,
[L"Chaga Mushroom"] = true,
[L"Crushed Glass"] = true,
[L"Crystal Shards"] = true,
[L"Crystalline Blackrock"] = true,
[L"Daemon Claw"] = true,
[L"Delicate Scales"] = true,
[L"Elven Fletching"] = true,
[L"Essence Of Achievement"] = true,
[L"Essence Of Balance"] = true,
[L"Essence Of Control"] = true,
[L"Essence Of Diligence"] = true,
[L"Essence Of Direction"] = true,
[L"Essence Of Feeling"] = true,
[L"Essence Of Order"] = true,
[L"Essence Of Passion"] = true,
[L"Essence Of Persistence"] = true,
[L"Essence Of Precision"] = true,
[L"Essence Of Singularity"] = true,
[L"Faery Dust"] = true,
[L"Goblin Blood"] = true,
[L"Lava Serpent Crust"] = true,
[L"Luminescent Fungi"] = true,
[L"Parasitic Plant"] = true,
[L"Powdered Iron"] = true,
[L"Raptor Teeth"] = true,
[L"Reflective Wolf Eye"] = true,
[L"Seed Of Renewal"] = true,
[L"Silver Snake Skin"] = true,
[L"Slith Tongue"] = true,
[L"Spider Carapace"] = true,
[L"Undying Flesh"] = true,
[L"Vial Of Vitriol"] = true,
[L"Void Orb"] = true,

[L"Ore"] = true,
}